"""empty message

Revision ID: 2ddcba264144
Revises: 71f129f07c96
Create Date: 2022-04-13 16:31:28.442923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ddcba264144'
down_revision = '71f129f07c96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=40), nullable=False))
    op.add_column('users', sa.Column('dog', sa.Boolean(), nullable=False))
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.drop_column('users', 'dog')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
